TOKEN = "DISCORD BOT TOKEN"
BOT_USERNAME = 'WHATEVER THE BOTS USERNAME IS INCLUDING NUMBERS (ex. Gravesbot #2824)'
BOT_ID = 'RIGHT CLICK THE BOT AND GET ITS ID'

TWITTER_CONSUMER_KEY = 'TWITTER CONSUER KEY'
TWITTER_CONSUMER_SECRET = "TWITTER CONSUMER SECRET"
TWITTER_ACCESS_TOKEN = "TWITTER ACCESS TOKEN"
TWITTER_ACCESS_TOKEN_SECRET = "TWITTER ACCESS TOKEN SECRET"

